### ISSUE TITLE
Please add a screen shot and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [lolkekdev/lkdev-CustomZsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name `zsh-theme` is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Thanks!

**Comment by lolkekdev** [comment]
@unixorn

**Comment by lolkekdev** [comment]
Done

**Comment by lolkekdev** [comment]
I think this name is good

**Comment by lolkekdev** [comment]
Sorry for closing the issue 2 times. I am writing from mobile phone now

**Comment by lolkekdev** [comment]
Also, I think, I'll update my theme by adding helpful aliases and some plugins

**Comment by lolkekdev** [comment]
Also screenshot will be added
